services:
  backend:
    build:
      context: .
      nixpacks:
        providers:
          - node
        config:
          cmds:
            - cd backend && npm install && npm start
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password@mongo:27017/product-feed?authSource=admin
      - JWT_SECRET=your_strong_secret_key_here
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=https://yourdomain.easypanel.host
      - REDIS_URI=redis://redis:6379
    volumes:
      - backend_data:/app/backend/public
    restart: always
    depends_on:
      - mongo
      - redis
    labels:
      - easypanel.expose=true
      - easypanel.expose.port=3001

  frontend:
    build:
      context: .
      nixpacks:
        providers:
          - node
        config:
          cmds:
            - cd frontend && npm install && npm run build && npm start
    environment:
      - NEXT_PUBLIC_API_URL=https://api.yourdomain.easypanel.host/api
      - NEXT_PUBLIC_NODE_ENV=production
    restart: always
    depends_on:
      - backend
    labels:
      - easypanel.expose=true
      - easypanel.expose.port=3000

  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=product-feed
    command: --wiredTigerCacheSizeGB 1

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  mongo_data:
  backend_data:
  redis_data:
